# Generated by Django 2.1.2 on 2019-01-23 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_author_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='newsarticle',
            name='image',
            field=models.ImageField(blank=True, default='https://picsum.photos/1100/700/?image=1067', null=True, upload_to=''),
        ),
    ]
