# Generated by Django 2.1.2 on 2019-01-23 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0003_newsarticle_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newsarticle',
            name='image',
        ),
        migrations.AddField(
            model_name='newsarticle',
            name='text',
            field=models.CharField(blank=True, default='https://picsum.photos/1100/700/?image=1067', max_length=250, null=True),
        ),
    ]
