# Generated by Django 2.1.2 on 2019-01-23 19:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20190123_1942'),
    ]

    operations = [
        migrations.RenameField(
            model_name='newsarticle',
            old_name='text',
            new_name='image',
        ),
    ]
