# Generated by Django 2.1.2 on 2018-10-10 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='HomeListing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=120)),
                ('city', models.CharField(max_length=120)),
                ('state', models.CharField(max_length=120)),
                ('zip_code', models.IntegerField()),
                ('number_of_bed', models.IntegerField(default=1)),
                ('number_of_bath', models.DecimalField(decimal_places=1, max_digits=10)),
                ('year_built', models.IntegerField()),
                ('sq_ft', models.IntegerField()),
            ],
        ),
    ]
