# Generated by Django 2.1.2 on 2018-10-11 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0003_auto_20181011_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='homelisting',
            name='cost',
            field=models.IntegerField(default=1),
        ),
    ]
