# Generated by Django 2.1.2 on 2018-10-18 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0006_auto_20181016_1631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='img',
            field=models.ImageField(blank=True, default='default_home_pic.jpg', null=True, upload_to='house_photos'),
        ),
    ]
