# Generated by Django 2.1.2 on 2019-01-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0010_auto_20190116_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='homelisting',
            name='img',
            field=models.ImageField(blank=True, default='beach.jpg', null=True, upload_to='house_photos'),
        ),
    ]
